/*
 * MCP Root CA Service
 * Service for maintaining a list of root CAs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@maritimeconnectivity.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Attestation;
import io.swagger.client.model.AttestationRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AttestationControllerApi
 */
@Ignore
public class AttestationControllerApiTest {

    private final AttestationControllerApi api = new AttestationControllerApi();

    /**
     * createAttestation
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAttestationUsingPOSTTest() throws ApiException {
        AttestationRequest body = null;
        Attestation response = api.createAttestationUsingPOST(body);

        // TODO: test validations
    }
    /**
     * getAttestation
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAttestationUsingGETTest() throws ApiException {
        Long id = null;
        Attestation response = api.getAttestationUsingGET(id);

        // TODO: test validations
    }
    /**
     * getAttestations
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAttestationsUsingGETTest() throws ApiException {
        List<Attestation> response = api.getAttestationsUsingGET();

        // TODO: test validations
    }
}
