/*
 * MCP Root CA Service
 * Service for maintaining a list of root CAs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@maritimeconnectivity.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Revocation;
import io.swagger.client.model.RevocationRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RevocationControllerApi
 */
@Ignore
public class RevocationControllerApiTest {

    private final RevocationControllerApi api = new RevocationControllerApi();

    /**
     * createRevocation
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createRevocationUsingPOSTTest() throws ApiException {
        RevocationRequest body = null;
        Revocation response = api.createRevocationUsingPOST(body);

        // TODO: test validations
    }
    /**
     * getRevocation
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRevocationUsingGETTest() throws ApiException {
        Long id = null;
        Revocation response = api.getRevocationUsingGET(id);

        // TODO: test validations
    }
    /**
     * getRevocations
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRevocationsUsingGETTest() throws ApiException {
        List<Revocation> response = api.getRevocationsUsingGET();

        // TODO: test validations
    }
}
