/*
 * MCP Root CA Service
 * Service for maintaining a list of root CAs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@maritimeconnectivity.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.RootCA;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RootCaControllerApi
 */
@Ignore
public class RootCaControllerApiTest {

    private final RootCaControllerApi api = new RootCaControllerApi();

    /**
     * createRootCA
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createRootCAUsingPOSTTest() throws ApiException {
        String body = null;
        RootCA response = api.createRootCAUsingPOST(body);

        // TODO: test validations
    }
    /**
     * getRootCA
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRootCAUsingGETTest() throws ApiException {
        Long id = null;
        RootCA response = api.getRootCAUsingGET(id);

        // TODO: test validations
    }
    /**
     * getRootCAs
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRootCAsUsingGETTest() throws ApiException {
        Long attestorId = null;
        List<RootCA> response = api.getRootCAsUsingGET(attestorId);

        // TODO: test validations
    }
}
